### ISSUE TITLE
Powershell Error on Windows 7

### ISSUE THREAD

**Issue by pedrodj** [JoelGMSec/AutoRDPwn#1]
Hi Joel,

***
PS C:\Python\AutoRDP> .\AutoRDPwn.ps1
Specificare un'espressione di valore sul lato destro dell'operatore '-'.
In C:\Python\AutoRDP\AutoRDPwn.ps1:63 car:145
+     default { Write-Host"" ; Write-Host "Wrong option, please try again" -ForegroundColor Magenta ; sleep -millisecon
ds 2000 }}} until ($input - <<<< in '1','2')
    + CategoryInfo          : ParserError: (:) [], ParseException
    + FullyQualifiedErrorId : ExpectedValueExpression
***

Thank you

**Comment by JoelGMSec** [comment]
Hi Pedro,

I'm currently developing the tool in Windows 10. Could you tell me which version of Windows 7 you are using and what version of Powershell? When I have a while I will try it on a vm to reproduce the error. As soon as I know something, I'll inform you.

Thanks a lot,

Regards.

**Comment by Atavic** [comment]
Check PowerShell version: run the *$PSVersionTable* command.

Windows 10 Anniversary Update comes with PowerShell 5.1

Microsoft has also made PowerShell 3.0 available for Windows 7 with Service Pack 1, while
Windows 7 had PowerShell 2.0

**Comment by Atavic** [comment]
Check PowerShell version: run the *$PSVersionTable* command.

Windows 10 Anniversary Update comes with PowerShell 5.1

Microsoft has also made PowerShell 5.1 available for Windows 7 with Service Pack 1, while
Windows 7 had PowerShell 2.0

**Comment by JoelGMSec** [comment]
To update Powershell to the latest version in Windows 7, here is the link: 

http://aka.ms/wmf5download

Tell me if works, regards.
