### ISSUE TITLE
English language support

### ISSUE THREAD

**Issue by cjs0h** [JoelGMSec/AutoRDPwn#4]
is there any plans to translate the script to english language ?

**Comment by JoelGMSec** [comment]
Hi cjs0h,

As can be seen in the description, the program currently works in both English and Spanish.

![autordpwn_en1](https://user-images.githubusercontent.com/34335312/49990174-02563880-ff7d-11e8-896f-894a961a5214.png)
![autordpwn_en2](https://user-images.githubusercontent.com/34335312/50776478-624cb000-1299-11e9-8771-8648f559afe5.png)

In the next version there will be support for many more languages, if you have any other idea let me know.

Regards!
