### ISSUE TITLE
about Windows Defender

### ISSUE THREAD

**Issue by huai201208** [JoelGMSec/AutoRDPwn#6]
"Automatic exclusion in Windows Defender (4 different methods)"
Where is the closing code? No seeing....
thanks~

**Comment by JoelGMSec** [comment]
Hi huai201208,

Currently, the four exclusions are the following:

• By PID
• By route (temp folder)
• By extension (.exe & .ps1)
• Deactivating the scanning of all downloaded files

The code would be the following:
Add-MpPreference -ExclusionExtension ".exe"
Add-MpPreference -ExclusionProcess $pid
Add-MpPreference -ExclusionPath $env:temp
Add-MpPreference -ExclusionExtension ".ps1"
Set-MpPreference -DisableIOAVProtection 1

You can find it actually on line 105, hope this helped you.

Regards!
